### Get all

GET http://localhost:8080/person
Accept: *

### Valid request
POST http://localhost:8080/person
Content-Type: application/json

{
  "name": "Ivan",
  "age": 18
}


### Invalid request
POST http://localhost:8080/person
Content-Type: application/json

{
  "age": 1
}
